project:
  type: website

website:
  navbar:
    left:
      - text: "![](assets/Logo.svg){height=2em}<b class='logo-title'>Br<b class='logo-ai'>AI</b>nstormer</b>"
        href: "/"
    right:
      - href: /brainstormer
        text: "<span class='btn btn-primary'>Jetzt Workarounds finden</span>"
        
format:
  html:
    theme:
      - litera
      - theme.custom.scss
    css: styles.css
    include-after-body: footer.html



