---
pagetitle: "Workaround Brainstormer"
format:
    html:
        toc: true
        toc-depth: 4
        toc-location: right
---


# Workaround Brainstormer
<a href="https://blog.viadee.de/changeworkaround-projektstart" target="_blank">
Dass Workarounds in Unternehmen stattfinden, steht fest.</a> 
Doch wie kann der Umgang mit diesen sinnvoll gestaltet werden? Zuerst gilt es sie zu identifizieren. </br>
Der <i>Workaround Brainstormer</i> kann Process Owner:innen oder anderen Stakeholdern helfen noch unbekannte, zielgerichtete Abweichungen eines Prozesses aufzudecken und plausible Hyothesen zu bilden.
</br>
Um das Tool auszuprobieren, können Sie auf den folgenden Button klicken. 
                
<a class="cta-button btn btn-secondary" target="_blank" href="/brainstormer">Jetzt Workarounds finden</a>

## Beispiel Coffee Coders Inc.


Input ist eine Beschreibung eines Geschäftsprozesses (hier stark vereinfacht - es könnte auch ein BPMN-Diagramm sein)

:::{.callout-note title="Vereinfachter Prozess"}
> ... in der IT-Beratung nehmen wir erst Kundenanforderungen auf. Dann geben wir Kaffee hinzu und erstellen Software-Lösungen.

:::



Als Output erhalten wir <i>Workaround-Stories</i> die in diesem Geschäftsprozess plausibel sind:


:::: {.coffee-image}

<div>

:::{.callout-tip title="Workaround-Stories"}
1.  Als Software-Entwickler bin ich unproduktiv, falls die Kaffeemaschine kaputt ist. Ich habe daher Instant-Kaffee in meinem Schreibtisch bevorratet, um mein Koffein-Level abzusichern.
2. Als Scrum-Masterin sind meine Meetings unproduktiv, wenn sich täglich eine Schlange an der Kaffeemaschine bildet. Ich bereite daher Filterkaffee für alle vor, um die Wartezeit zu verringern.
3. Als Software-Entwicklerin bin ich unkonzentriert, falls die Kaffeemaschine ausfällt. Ich weiche daher auf Tee aus, um meine Deadlines zu erreichen.
4. Als Software-Architektin bin ich unkonzentriert, falls die Kaffeemaschine ausfällt oder die Schlange vor der Maschine zu lang ist. Ich bleibe daher lieber im Homeoffice, um unabhängig von der Kaffeemaschine und der Warteschlange zu sein.
:::

</div>

{{< video assets/wa_brainstormer_erklaervideo.mp4 width="450" >}}


::::
Wir bekommen einen Überblick über potenziell beteiligte Personen und deren "Misfits", also Sorgen und Herausforderungen und insb. externe Rahmenbedingungen, die sie dazu bringen vom Sollprozess abzuweichen. Einige davon sind nicht wünschenswert (Software-Architektin nur im Home-Office) andere können Keimzelle eines angepassten Soll-Prozesses sein (die strategische Instant-Kaffee-Reserve). 



## Forschungskontext

### Workarounds als Mittel für Wettbewerbsfähigkeit

Der Workaround Brainstormer ist ein Zwischenergebnis des Projektes Change.WorkAROUND, einem vom Bundesministerium für Bildung und Forschung (BMBF) geförderten Projekt. Das Projekt adressiert den wachsenden Bedarf nach Wandlungsfähigkeit in der Industrie, welche mit kürzeren Innovationszyklen und disruptiven globalen Ereignissen wie der COVID-19 Pandemie und der Energiewende konfrontiert wird. Oft finden operative Mitarbeitende kreative Lösungen, die Grundlage von Prozessinnovationen werden können, wenn der Soll-Prozess (rechtzeitig) davon erfährt.

Das Projekt zielt auf neue Methoden, Werkzeuge und Organisationskonzepte, um diese Workarounds zu erkennen, zu bewerten und in Prozessinnovationen umzusetzen.

### Wie Workarounds finden?

Trotz ihres potenziellen Werts bleiben Workarounds häufig in den Arbeitsabläufen des Unternehmens verborgen oder unentdeckt. In der Regel sind sie undokumentiert, informell und entgehen der Aufmerksamkeit der Prozessverantwortlichen.
Mit geeigneter Datengrundlage können solche Prozessveränderungen per Process Mining gefunden werden – oft gibt es eine solche Grundlage aber nicht, da Workarounds außerhalb von IT-Systemen auftreten oder informelle Kommunikationskanäle nutzen. Die Identifizierung dieser latenten Umgehungslösungen stellt deshalb eine große Herausforderung dar. So kann ein Mitarbeiter beispielsweise persönliche Messaging-Apps verwenden. Mitarbeiterbefragungen sind zwar wertvoll, liefern aber ein unvollständiges Bild, da Mitarbeitende oft nicht bereit sind, ihr nicht-standardgemäßes Verhalten offenzulegen (sei es aus Angst, Zeitmangel oder fehlender Initiative).
Können moderne LLMs vielleicht helfen, für einen Geschäftsprozess gezielt Hypothesen zu bilden – abzuschätzen, welche Workarounds es vermutlich geben wird?

### Lösungsansatz: Latente Workarounds und erste Erfahrungen
Erstaunlich oft gelingt das. Der Workaround Brainstormer ist ein Werkzeug, das diesen kreativen Prozess leicht und interaktiv macht.

Anhand einer textuellen Prozessbeschreibung oder eines BPMN-Diagramms bietet er die Möglichkeit, individuelle und domänenspezifische Workarounds mit nur wenigen Mausklicks zu generieren. Der Ansatz ist hierbei wie folgt: Die Prozessbeschreibung und (optional) weiterer Kontext werden in einen speziellen Prompt eingefügt, welcher das LLM instruiert, systematisch Workarounds zu identifizieren. Der Prompt enthält zusätzlich mehrere Workaround-Beispiele (few-shot-examples), um die Ergebnisse des LLM zu verbessern. Diese Beispiele können mithilfe eines RAG-Systems, welches auf eine Wissensdatenbank mit knapp 83 von Unternehmen validierten Workarounds zugreift, erweitert werden.

In der aktuellen Version des Werkzeugs werden Ihre Dateien nicht gespeichert, d.h. Ihre Prozessbeschreibung sowie die generierten Workarounds durchlaufen den Zyklus von Ihrem Webbrowser bis zu dem von uns gehosteten LLM in Azure.

Erste Erfahrungen und Experimente, in denen die Qualität und allgemeine Nutzbarkeit der Workarounds untersucht wurde, zeigen positive, aber vorläufige Ergebnisse. So wurden in einem Experiment, in dem 62 Personen (Anwender aus Industrieunternehmen, Mitglieder des Forschungskonsortiums, Mitarbeiter eines Beratungsunternehmens sowie Studenten) insgesamt 83 Workaround-Storys vorgestellt wurden, herausgefunden, dass die mit KI generierten Workarounds auf einem ähnlichen Qualitätsniveau wie die von informierten Personen sind. Weiter zeigen die Erfahrungen, dass die mit dem Brainstormer identifizierten Workarounds in wenigen Fällen tatsächlich in Unternehmen existieren und somit verwertet werden können. Genau dies ist das optimale Ergebnis bei der Nutzung des Tools – latente Workarounds identifizieren, um sie anschließend bewerten und ultimativ Prozessinnovationen erreichen zu können.

Folgend sollte der Workaround Brainstormer nicht als isoliertes Tool, sondern als ein Kreativitätswerkzeug betrachtet werden, welches in Verbesserungsinitiativen wertvolle Impulse gibt, die anschließend in Expertengruppen bewertet und diskutiert werden.


### Beispielhafte Nutzungsszenarien
Wir sehen vor allem zwei Nutzungsszeanarien für den Workaround Brainstormer:
            
- Das interaktive, leicht verständliche Interface erlaubt die Nutzung in Workshop-Situationen in einem Team, dass sich mit Prozess-Optimierungen oder Compliance-Fragen zu einem bestehenden Geschäftsprozess beschäftigt. Der Workshop endet mit einer Auswahl an Hypothesen zu existierenden Workarounds. Ob sie tatsächlich existieren, ist im nächsten Schritt zu prüfen.
- Da der Workaround Brainstormer anders als Data Mining-Verfahren nur eine Prozessbeschreibung voraussetzt und keine Event-Daten, nutzen Prozessverantwortliche ihn auch, um vor Inbetriebnahme eines neuen Prozesses zu prüfen, welche Umwelteinflüsse die Prozessbeteiligten potenziell beeinflussen werden und wie sie darauf vermutlich reagieren.
 
### Ausblick – Weiterentwicklung des Brainstormers

Der Brainstormer ist ein Ergebnis der in den letzten drei Jahren im Rahmen des Projektes Change.WorkAROUND geleisteten Forschungsarbeit. Da allerdings die Forschung noch nicht abgeschlossen ist und bei der Weiterentwicklung des Brainstormers noch viel Gestaltungsspielraum besteht, möchten wir für die Nutzung des Tools einschließlich für das Geben von Feedback appellieren. Mit Ihrem <a target="__blank" href="https://forms.office.com/pages/responsepage.aspx?id=uRWItZkdCkeisbP9f2Y9thOIGj0hKMNNi0kBX1tWIEFUMVY3RkRUQzZTTzFLVTY5Qkw0QVpFVlQ3OS4u&route=shorturl">Feedback</a> können Sie uns helfen, das Werkzeug weiter zu verfeinern und im Idealfall mehr Prozessinnovationen zu schaffen.

Ein zentraler Baustein des Werkzeugs ist unsere Wissensdatenbank von in Geschäftsprozessen beobachteten Workarounds und die Erkenntnis, dass ähnliche Workarounds unternehmensübergreifend immer wieder auftauchen. Diese Sammlung von Workarounds darf daher gern wachsen. Wir freuen uns über Ihre Workarounds – gern als Beitrag im <a target="__blank" href="https://github.com/viadee/workaround-brainstormer/issues">GitHub</a> oder sprechen Sie uns an: Frank.Koehne@viadee.de / <a href="https://www.linkedin.com/in/frank-köhne-9b586395" target="__blank">LinkedIn</a>.

## Benutzerhandbuch

Folgendes Handbuch beschreibt die Funktionalitäten des Brainstormers zur Generierung und Löschung von Workarounds sowie zur Anpassung des dem LLM übergebenden Prompts.

### Primäre Komponenten der Benutzeroberfläche
Die Workarounds werden grundsätzlich mithilfe eines gerichteten Graphs zentral auf der Benutzeroberfläche visualisiert. Dieser Graph dient als zentrale Erkundungsschnittstelle der Workarounds und kann während der Nutzung erweitert werden.

Das Prozesseingabefeld, oben rechts dargestellt, verwaltet die textuelle sowie visuelle Prozessbeschreibung, wobei letzteres mit einem Klick auf „click to browse“ als auch mit dem Ziehen und Ablegen des Bildes hochgeladen werden kann.

Die Workaround-Liste stellt die dritte Komponente unten rechts auf der Oberfläche dar. Hier werden die generierten Workarounds geschachtelt dargestellt. Rechts neben der Überschrift befindet sich außerdem ein Button für das Exportieren der Workarounds.


### Workarounds generieren

#### Initiale Workarounds generieren
Nachdem Sie Ihre Prozessbeschreibung oben rechts textuell eingegeben oder als BPMN-Diagramm hochgeladen haben, können Sie mit einem Klick auf den grünen Button „Generate Workarounds“ die initialen fünf Workarounds generieren.

#### Kind-Workarounds generieren
Nachdem die ersten Workarounds generiert wurden, können mit einem Linksklick fünf weitere Kind-Workarounds erzeugt werden. Mittels eines zweiten Prompts werden hierbei ähnliche Workarounds erzeugt, welche dieselbe Praktikabilität des Vaters beibehalten, ähnliche Problemtypen adressieren und ähnliche Vorteile erzielen, allerdings Variationen in die betrachteten Rollen sowie in die verwendeten Ressourcen und Vorgehensweisen bringen.

### Workarounds entfernen
Mit einem Rechtsklick auf einen Knoten im Graph wird das Kontextmenü geöffnet – hier können Knoten und Unterknoten entfernt werden.

### Zusätzlichen Kontext hinzufügen
Die Prompts können neben der Prozessbeschreibung mit zusätzlichen Informationen angereichert werden, welche für die Workaround-Generierung relevant sein könnte. Dies kann zusätzliche Informationen über das Unternehmen, die im Prozess involvierten Rollen, Umstände oder bestimmte, für den Nutzer besonders interessante Themen sein.
Der Button oben rechts neben der Überschrift „Process Description“ zeigt hierfür bei einem Rechtsklick ein zusätzliches Eingabefeld „Additional Context“ an, in dem die Informationen eingegeben werden können.

### Few-shot Examples bearbeiten
Unter dem im vorherigen Punkt beschriebenen Eingabefeld befindet sich ein Button „Edit Few Shot Examples“. In diesem Dialog können die dem Prompt übergebenden Beispiele bearbeitet, entfernt und neue hinzugefügt werden.

### Eingebettete Workaround-Beispiele hinzufügen
Der Brainstormer bietet die Möglichkeit, basierend auf der Prozessbeschreibung, den Prompt um weitere Workaround-Beispiele zu ergänzen. Mit einem Klick auf den Button „Retrieve similar Few Shot Examples“ werden aus in einer Vektordatenbank eingebetteten Workarounds ähnliche abgerufen und dem Prompt beigefügt.

## FAQ

:::{.callout-tip collapse="true"}
### Was genau ist mit Workaround gemeint?

Ein Workaround ist wissenschaftlich gesehen eine zielgerichtete Anpassung, Improvisation oder sonstige Änderung eines eines bestehenden Arbeitssystems, um Hindernisse, Ausnahmen [..] zu überwinden oder zu umgehen [..] die seine Teilnehmer daran hindern, ein gewünschtes Maß an Effizienz, Effektivität oder andere organisatorische oder persönliche Ziele zu erreichen (<a href="https://aisel.aisnet.org/cais/vol34/iss1/55/">Alter, 2014</a>).

Workarounds sind damit nicht per se schlecht, sondern können sich auch als kreative Lösungen zur Verbesserung von Prozessen oder zur Erreichung von Zielen betrachtet herausstellen. Wir empfehlen daher, die Identifikation und die Bewertung von Workarounds voneinander zu trennen. 
:::

:::{.callout-tip collapse="true"}
### Was sind Workaround-Storys?

Workaround-Storys fassen (angelehnt an das bekannt User-Story-Format) die Schlüsselelemente <i>Actor</i>, <i>Context</i>, <i>Challenge or Misfit</i>, <i>Adaptive Action</i> sowie <i>Intended Outcome</i> in einer einzigen, kohärenten Aussage zusammen und vermitteln gleichzeitig ausreichend Informationen für Analysezwecke. Dies ermöglicht den einfachen Austausch von Workarounds und die Ähnlichkeitssuche per LLM.
:::
:::{.callout-tip collapse="true"}
### Wie gut sind die Ergebnisse?

Hier ist wichtig zu verstehen, was ein gutes Ergebnis ist. Der Workaround-Brainstormer erzeugt <i>plausible</i> Hypothesen. Das bedeutet, dass die generierten Workarounds vermutlich im beschriebenen Geschäftsprozess <b>existieren</b>. Das sagt Nichts darüber aus, ob sie nützliche Prozessinnovationen darstellen (Meistern neuer Herausforderungen) oder aus unterschiedlichsten Gründen nicht wünschenswert sind (Schatten-IT, Compliance-Verletzungen etc.). Das zu entscheiden wäre der nächste (manuelle) Prozessschritt.<br/>
In diesem Sinne sind die Ergebnisse gut, denn für detailliert beschrieben Prozesse können Menschen i.A. die generierten Vorschläge nicht von menschlichen Vorschlägen unterscheiden.
:::
:::{.callout-tip collapse="true"}
### Wie genau muss ich den Prozess beschreiben?

Das ist flexibel und hier wird die Stärke des LLM-Ansatzes sichtbar. Oft sind mit wenigen Sätzen schon gute Ergebnisse zu erzielen. Je mehr Details Sie angeben, desto besser werden die Ergebnisse. Das LLM ist in der Lage, auch BPMN-Diagramme zu verarbeiten. Diese werden dann in Text umgewandelt und als Prozessbeschreibung verwendet. Auch mit Bildern von Prozessen oder Arbeitsplätzen oder einer Kombination dieser Elemente haben wir gute Ergebnisse bekommen.<br/>
Eine Erkenntnis aus dem Projekt ist, dass Workarounds häufig auf einem Detail-Level stattfinden, das in BPMN-Diagrammen und formalen Prozessbeschreibungen nicht abgebildet ist (bspw. "Sicherheitshandschuhe vergessen"). Daher ist es sinnvoll, auch die Prozessbeschreibung zu verwenden, um sehr konkrete Arbeitssituationen und Arbeitsplätze zu verdeutlichen. 
:::
