---
pagetitle: "Nutzungsbedindungen"
---


# Nutzungsbedindungen
Stand: 12.05.2025


## Lizenz
Copyright 2025 viadee Unternehmensberatung AG </br>
 https://opensource.org/license/bsd-3-clause </br> 
 
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: 

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. 
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

## AI Governance
Der Workaround Brainstormer ist ein KI-System im Sinne des EU AI Acts.
Es handelt sich um ein KI-System mit dem einzigen Einsatzzweck wissenschaftlicher Forschung, per Artikel 2 Absatz 6.
Es handelt sich um ein Open Source-System außerhalb der Hochrisiko-Kategorie, per Artikel 2 Absatz 12. Es ergeben sich daher keine weiteren Anforderungen aus dem EU AI Act.

Dennoch möchten wir im Sinne der Transparenz klarstellen:

- Das System generiert plausible Hypothesen für potenziell in Geschäftsprozessen existierende Workarounds. Diese können falsch oder missverständlich sein und entstehen nicht-deterministisch. Sie sind keine Vorschläge Prozesse zu verändern, sondern Hypothesen dazu, welche Prozessveränderungen vielleicht ohnehin schon unbemerkt erfolgt sind.
- Das System verwendet in der von viadee betriebenen Version ein per Azure Ai Foundry bereitgestelltes, in der EU betriebenes LLM.
- Es findet kein Training mit den von Nutzer:innen bereitgestellten Daten statt. viadee hat keinen Einblick in die von Nutzer:innen bereitgestellten Daten (mit Ausnahme von explizit gegebenem Feedback).

Die durch das System generierten Hypothesen sind nicht urheberrechtlich geschützt und können beliebig weiterverwendet werden.

## Acceptable Use
Die viadee Unternehmensberatung AG betreibt eine Installation des Open Source-Werkzeuges *Workaround Brainstormer*, um Feedback zu ermöglichen. Die Nutzung der bereitgestellten Installation ist im angemessenen Maße zulässig.

Die Nutzung des Workaround Brainstormers erfolgt auf eigene Verantwortung. viadee übernimmt keine Haftung für Schäden oder Verluste, die aus der Nutzung, fehlerhaften Hypothesen oder der Nichtverfügbarkeit des Systems resultieren, soweit gesetzlich zulässig. Unangemessen und nicht zulässig sind folgende Nutzungsweisen:

- Jegliche Nutzung zu illegalen, unethischen oder gegen geltendes Recht verstoßenden Zwecken ist untersagt.
- Übermäßige Nutzungsintensität, im Sinne von Nutzungsfrequenz und Umfang bereitgestellter Prozessbeschreibungen, über das für die Vorbereitung und Durchführung von Workshops notwendige Maß hinaus.
- Insb. ist eine automatisierte Nutzung des Werkzeuges unzulässig (dies setzt eine eigene Installation voraus).
- Die Einbettung der Installation in andere Werkzeuge ist unzulässig (dies setzt eine eigene Installation voraus).

Die Nutzer:innen sind verpflichtet, keine personenbezogenen oder vertraulichen Daten in das System einzugeben. Die Verantwortung für die Einhaltung datenschutzrechtlicher Vorgaben liegt ausschließlich bei den Nutzer:innen.
Es besteht kein Anspruch auf Support, Wartung oder Weiterentwicklung der Installation.

## Umgang mit Feedback

Nutzer:innen haben die Möglichkeit, über ein Feedback-Formular (via MSForms) anonym Kommentare und Anregungen zu übermitteln.

Durch die Übermittlung von Feedback gewähren Nutzer:innen viadee ein uneingeschränktes, unbefristetes und räumlich unbegrenztes Nutzungsrecht an allen eingereichten Inhalten. Dies schließt ausdrücklich die Nutzung zu Forschungszwecken und die Veröffentlichung der Inhalte ein.

viadee behält sich das Recht vor, diese Nutzungsbedingungen jederzeit zu ändern. Änderungen werden auf dieser Webseite bekannt gegeben.